define([
    './mod',
    'homeCtrl',
    'highchartsCtrl',
    'loginCtrl',
    'registerCtrl',
    'retrieveCtrl',
    'mycenterCtrl',
    'searchPeopleCtrl',
    'litigationCtrl',
    'shareholderCtrl',
]);
