define([
    './mod',
    'userService',
    'suggestionFeedbackService',
    'investAbroadService',
    'industryService',
    'enterpriseService',
    'reviseUserService',
    'authService',
    'searchPeopleService',
    'echartsService',
    'businessMapService',
    'annualReportService',
    'jobService'
]);
